<!DOCTYPE html><html><head><title>Pip ReadTimeoutError in Windows 10</title></head><link href='style.css' rel='stylesheet' ><link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'><body><h2><a href='//stackoverflow.com/a/54832235'>Pip ReadTimeoutError in Windows 10</a></h2><p class='feedback'></p><br /><pre style='border:1px solid black;border-radius:5px'><code><p>I am also having trouble like this.</p>

<p>I get: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/</p>

<p>Does anyone have an answer?</p>
</code></pre><p>Posted by <a href='https://stackoverflow.com/users/10997264'>Jake Kelly</a> (13) at 2019-02-22T17:26:08Z</p><p>Caught for</p>Contains Blacklisted Word - trying<br/>Ends with ?<br/>Low Length<br/>No Code Block<br/>IntelliBL - -2.0<br/>Low Rep<br/></body></html>
